var minify = require('html-minifier').minify;
var fs = require('fs');
var HF = {
    minifyHtml: function (data) {
        return minify( data , {
            conservativeCollapse: true,
            collapseWhitespace: true,
            trimCustomFragments: true,
            useShortDoctype: true,
            collapseInlineTagWhitespace: true,
            // removeEmptyElements: true,
            removeComments: true,
            processConditionalComments: true,
            removeEmptyAttributes: true,
            removeRedundantAttributes: true,
            includeAutoGeneratedTags: true,
            html5: true,
            minifyCSS: true,
            minifyJS: true,
            preserveLineBreaks: true
        });
    }, readFile: function (url) {
        return fs.readFileSync(url).toString();
    }
};
module.exports = HF;