var minify = require('html-minifier').minify;
var fs = require('fs');
var HF = {
    minifyHtml: function (data) {
        return minify( data , {
            conservativeCollapse: true,
            collapseWhitespace: true,
            trimCustomFragments: true,
            useShortDoctype: true,
            collapseInlineTagWhitespace: true,
            // removeEmptyElements: true,
            removeComments: true,
            processConditionalComments: true,
            removeEmptyAttributes: true,
            removeRedundantAttributes: true,
            includeAutoGeneratedTags: true,
            html5: true,
            minifyCSS: true,
            minifyJS: true,
            preserveLineBreaks: true
        });
    }, readFile: function (url) {
        return fs.readFileSync(url).toString();
    }, writeFile: function (data, url) {
        fs.writeFileSync(url, data);
    }, replaceText: function (data, from, to) {
        return data.replace( new RegExp(from, 'g'), to );
    }, replaceTextDir: function (data, dir) {
        return data.replace( new RegExp('%dir%', 'g'), dir );
    }, appendJsToStart: function (data, js) {
        return data.replace( new RegExp('<body>', 'g'), '<body><script>' + js + '</script>');
    }, appendJsToFinish: function (data, js) {
        return data.replace( new RegExp('</body>', 'g'), '<script>' + js + '</script></body>');
    }, appendCssToStart: function (data, css) {
        return data.replace( new RegExp('<body>', 'g'), '<body><style>' + css + '</style>');
    }, appendCssToFinish: function (data, css) {
        return data.replace( new RegExp('</body>', 'g'), '<style>' + css + '</style></body>');
    }
};
module.exports = HF;