var minify = require('html-minifier').minify;
var fs = require('fs');
var imagemin = require('imagemin');
// var imageminJpegtran = require('imagemin-jpegtran');
// var imageminPngquant = require('imagemin-pngquant');
var gulp = require('gulp');
var imagemin = require('gulp-imagemin');
var image = require('gulp-image');
var path = require('path');

var HF = {
    minifyHtml: function (data) {
        var newData = minify( data , {
            conservativeCollapse: true,
            collapseWhitespace: true,
            trimCustomFragments: true,
            useShortDoctype: true,
            collapseInlineTagWhitespace: true,
            // removeEmptyElements: true,
            removeComments: true,
            processConditionalComments: true,
            removeEmptyAttributes: true,
            removeRedundantAttributes: true,
            includeAutoGeneratedTags: true,
            html5: true,
            minifyCSS: true,
            minifyJS: true,
            preserveLineBreaks: true
        });
        return newData
    }, readFile: function (url) {
        return fs.readFileSync(url).toString();
    }, writeFile: function (data, url) {
        fs.writeFileSync(url, data);
    }, replaceText: function (data, from, to) {
        return data.replace( new RegExp(from, 'g'), to );
    }, replaceTextDir: function (data, dir) {
        return data.replace( new RegExp('%dir%', 'g'), dir );
    }, appendJsToStart: function (data, js) {
        return data.replace( new RegExp('<body>', 'g'), '<body><script>' + js + '</script>');
    }, appendJsToFinish: function (data, js) {
        return data.replace( new RegExp('</body>', 'g'), '<script>' + js + '</script></body>');
    }, appendCssToStart: function (data, css) {
        return data.replace( new RegExp('<body>', 'g'), '<body><style>' + css + '</style>');
    }, appendCssToFinish: function (data, css) {
        return data.replace( new RegExp('</body>', 'g'), '<style>' + css + '</style></body>');
    }, compressImg: function (url) {
        try {
            // imagemin([url + '/*.{jpg,png}'], url, {
            //     plugins: [
            //         imageminJpegtran(),
            //         imageminPngquant({quality: '1-2'})
            //     ]
            // });
        } catch (err) {
            console.warn('compressImg err: ', err);
        }
    }, compressImgGulp: function (url) {
        try {
            gulp.src( path.join(url, '*') )
                .pipe(image({
                    pngquant: true,
                    optipng: true,
                    zopflipng: true,
                    jpegRecompress: true,
                    jpegoptim: true,
                    mozjpeg: true,
                    guetzli: false,
                    gifsicle: true,
                    svgo: true,
                    concurrent: 10
                }))
                .pipe(gulp.dest(url))
        } catch (err) {
            console.warn('compressImgGulp err: ', err);
        }
    }
};
module.exports = HF;